import { UserRole } from "@/lib/middle/roles";

export const PERMISSIONS = {
  VIEW_USERS: "VIEW_USERS",
  ADD_USERS: "ADD_USERS",
  UPDATE_USERS: "UPDATE_USERS",
  DELETE_USERS: "DELETE_USERS",
  VIEW_CATEGORIES: "VIEW_CATEGORIES",
  MANAGE_CATEGORIES: "MANAGE_CATEGORIES",
  MANAGE_POSTS: "MANAGE_POSTS",
  VIEW_POSTS: "VIEW_POSTS",
  PUBLISH_POSTS: "PUBLISH_POSTS",
  DELETE_POSTS: "DELETE_POSTS",
  ADMIN_CONTROLLED_DATA: "ADMIN_CONTROLLED_DATA",
} as const;

// Define The Type Of Permissions
const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.ADD_USERS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.ADMIN_CONTROLLED_DATA,
    PERMISSIONS.UPDATE_USERS,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.MANAGE_POSTS,
    PERMISSIONS.VIEW_POSTS,
    PERMISSIONS.PUBLISH_POSTS,
    PERMISSIONS.DELETE_POSTS,
    // PERMISSIONS.MANAGE_SETTINGS,
  ],
  [UserRole.AUTHOR]: [PERMISSIONS.VIEW_POSTS],
  [UserRole.USER]: [PERMISSIONS.VIEW_POSTS],
  [UserRole.SUBSCRIBER]: [PERMISSIONS.VIEW_POSTS],
};

// Check permission
export function hasPermission(role: UserRole, permission: string): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) || false;
}
